_format_version: "3.0"

services:
  - name: user-management-service
    url: http://user-management-service:3000
    routes:
      - name: user-management-route
        paths:
          - /user-management
