name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build www
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0
        with: 
          node-version: 18
            
      - name: Install Dependencies
        run: npm install --prefix www

      - name: Build
        run: npm run build --prefix www
